## Will Dodge  2018-02-05


### import packages:

In [1]:
from datetime import datetime
from dateutil.parser import parse
import pandas as pd

### read csv file:

In [2]:
filename = 'C:\\crop_modeling\\weather_lbk.csv'
data = pd.read_csv(filename)

### perform calculations:

In [3]:
data['Date'] = pd.to_datetime(data['Date'], format='%m/%d/%Y')
data['dGDU'] = ((data['Temp_High']+data['Temp_Low'])/2)-10
data['accu_dGDU'] = data['dGDU'].cumsum()

### view data to be sure it looks right:

In [4]:
data

     Year  DOY  Temp_High   Temp_Low       Date       dGDU    accu_dGDU
0    2017  157      31.02  23.426424 2017-06-06  17.223212    17.223212
1    2017  158      29.72  22.907257 2017-06-07  16.313628    33.536840
2    2017  159      31.24  23.799271 2017-06-08  17.519635    51.056476
3    2017  160      32.43  23.815486 2017-06-09  18.122743    69.179219
4    2017  161      35.99  27.388229 2017-06-10  21.689115    90.868333
5    2017  162      35.86  27.970174 2017-06-11  21.915087   112.783420
6    2017  163      36.12  27.273438 2017-06-12  21.696719   134.480139
7    2017  164      36.39  27.482118 2017-06-13  21.936059   156.416198
8    2017  165      36.85  27.927361 2017-06-14  22.388681   178.804878
9    2017  166      36.04  25.806215 2017-06-15  20.923108   199.727986
10   2017  167      37.34  28.042882 2017-06-16  22.691441   222.419427
11   2017  168      42.20  31.148333 2017-06-17  26.674167   249.093594
12   2017  169      27.58  22.772778 2017-06-18  15.176389   264.269983
13   2017  170      29.84  23.267604 2017-06-19  16.553802   280.823785
14   2017  171      34.60  27.743715 2017-06-20  21.171858   301.995642
15   2017  172      35.86  28.509375 2017-06-21  22.184687   324.180330
16   2017  173      36.29  27.835833 2017-06-22  22.062917   346.243247
17   2017  174      34.02  28.055764 2017-06-23  21.037882   367.281128
18   2017  175      26.55  20.570069 2017-06-24  13.560035   380.841163
19   2017  176      29.45  22.988264 2017-06-25  16.219132   397.060295
20   2017  177      27.33  21.194549 2017-06-26  14.262274   411.322569
21   2017  178      31.04  24.157951 2017-06-27  17.598976   428.921545
22   2017  179      34.45  27.225069 2017-06-28  20.837535   449.759080
23   2017  180      39.59  29.351389 2017-06-29  24.470694   474.229774
24   2017  181      35.53  27.858681 2017-06-30  21.694340   495.924115
25   2017  182      28.25  23.214757 2017-07-01  15.732378   511.656493
26   2017  183      31.34  24.249826 2017-07-02  17.794913   529.451406
27   2017  184      32.15  23.836632 2017-07-03  17.993316   547.444722
28   2017  185      32.55  23.701285 2017-07-04  18.125642   565.570365
29   2017  186      29.55  23.576736 2017-07-05  16.563368   582.133733
..    ...  ...        ...        ...        ...        ...          ...
86   2017  244      29.45  21.035174 2017-09-01  15.242587  1593.539335
87   2017  245      31.32  22.915521 2017-09-02  17.117760  1610.657096
88   2017  246      30.96  22.288438 2017-09-03  16.624219  1627.281315
89   2017  247      32.40  23.400694 2017-09-04  17.900347  1645.181662
90   2017  248      24.05  19.138681 2017-09-05  11.594340  1656.776002
91   2017  249      25.36  17.929375 2017-09-06  11.644687  1668.420690
92   2017  250      28.20  19.547986 2017-09-07  13.873993  1682.294683
93   2017  251      28.15  20.007596 2017-09-08  14.078798  1696.373480
94   2017  252      27.41  19.037396 2017-09-09  13.223698  1709.597178
95   2017  253      27.44  19.047187 2017-09-10  13.243594  1722.840772
96   2017  254      29.86  20.402674 2017-09-11  15.131337  1737.972109
97   2017  255      33.55  22.773924 2017-09-12  18.161962  1756.134071
98   2017  256      32.88  23.975729 2017-09-13  18.427865  1774.561935
99   2017  257      34.46  24.342708 2017-09-14  19.401354  1793.963290
100  2017  258      32.95  24.415417 2017-09-15  18.682708  1812.645998
101  2017  259      33.38  22.682326 2017-09-16  18.031163  1830.677161
102  2017  260      27.16  20.175243 2017-09-17  13.667622  1844.344783
103  2017  261      31.03  22.053333 2017-09-18  16.541667  1860.886449
104  2017  262      33.70  24.878819 2017-09-19  19.289410  1880.175859
105  2017  263      30.20  23.263056 2017-09-20  16.731528  1896.907387
106  2017  264      33.54  24.773171 2017-09-21  19.156585  1916.063972
107  2017  265      28.24  22.015223 2017-09-22  15.127611  1931.191584
108  2017  266      28.26  22.893993 2017-09-23  15.576997  1946.768580
109  2017  267      23.96  20.510069 2017-09-24  12.235035  1959.003615
110  2017  268      21.81  18.780000 2017-09-25  10.295000  1969.298615
111  2017  269      16.29  14.826354 2017-09-26   5.558177  1974.856792
112  2017  270      16.76  14.539338 2017-09-27   5.649669  1980.506461
113  2017  271      14.89  13.961389 2017-09-28   4.425694  1984.932155
114  2017  272      16.66  14.019792 2017-09-29   5.339896  1990.272051
115  2017  273      16.82  15.503472 2017-09-30   6.161736  1996.433787

[116 rows x 7 columns]

### write file:

In [ ]:
data.to_csv('C:\\crop_modeling\\weather_lbk_OUT.csv')